user_menu : "ฺฉุงุฑุจุฑ {} ุนุฒุฒ ูุทูุงู ฺฏุฒูู ููุฑุฏ ูุธุฑ ุฎูุฏ ุฑุง ุจุฑุง ุงุฏุงูู ุงูุชุฎุงุจ ฺฉูุฏ ๐ :"
username_req : "ูุงู ุงุดุชุฑุงฺฉ ุฎูุฏ (  username )  ุฑุง ูุงุฑุฏ ฺฉูุฏ ."
password_req : "ุฑูุฒ ุนุจูุฑ  ุงุดุชุฑุงฺฉ ุฎูุฏ ( password ) ุฑุง ูุงุฑุฏ ฺฉูุฏ ."